version: '1'

services:
  web:
    build: .
    container_name: flask_app
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_IDENTITY_CLAIM=${JWT_IDENTITY_CLAIM}
      - JWT_TOKEN_LOCATION=${JWT_TOKEN_LOCATION}
      - JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - LOG_FILE_MAX_BYTES=${LOG_FILE_MAX_BYTES}
      - LOG_FILE_BACKUP_COUNT=${LOG_FILE_BACKUP_COUNT}
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - redis
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: